#!/bin/bash
cd /Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/outputs/1_1 && /Users/zyhuggan/bootcamp/rosetta/source/bin/relax.default.macosclangrelease @/Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/inputs/relax_inputs.flags
cd /Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/outputs/1_2 && /Users/zyhuggan/bootcamp/rosetta/source/bin/relax.default.macosclangrelease @/Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/inputs/relax_inputs.flags
cd /Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/outputs/1_3 && /Users/zyhuggan/bootcamp/rosetta/source/bin/relax.default.macosclangrelease @/Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/inputs/relax_inputs.flags
cd /Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/outputs/2_1 && /Users/zyhuggan/bootcamp/rosetta/source/bin/relax.default.macosclangrelease @/Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/inputs/relax_inputs.flags
cd /Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/outputs/2_2 && /Users/zyhuggan/bootcamp/rosetta/source/bin/relax.default.macosclangrelease @/Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/inputs/relax_inputs.flags
cd /Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/outputs/2_3 && /Users/zyhuggan/bootcamp/rosetta/source/bin/relax.default.macosclangrelease @/Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/inputs/relax_inputs.flags
cd /Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/outputs/3_1 && /Users/zyhuggan/bootcamp/rosetta/source/bin/relax.default.macosclangrelease @/Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/inputs/relax_inputs.flags
cd /Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/outputs/3_2 && /Users/zyhuggan/bootcamp/rosetta/source/bin/relax.default.macosclangrelease @/Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/inputs/relax_inputs.flags
cd /Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/outputs/3_3 && /Users/zyhuggan/bootcamp/rosetta/source/bin/relax.default.macosclangrelease @/Users/zyhuggan/bootcamp/pyrosetta_scripts/pilot/apps/zyajahuggan/lab_7/inputs/relax_inputs.flags
